---
ID: "345d217c-0dff-4d0c-907b-64c6842add2a"
Parent: "aedc3cc4-f609-448b-bf7f-2148560c5680"
Template: "aedc3cc4-f609-448b-bf7f-2148560c5680"
Path: /sitecore/templates/Project/demo/Rendering Parameters/Hero Banner Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "727efc64-29a2-44d2-ac14-54e3b86a22eb"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\asit_pani@epam.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250818T210919Z
