---
ID: "989f91cc-9c6f-4e17-a68b-62444156a9a1"
Parent: "a2b91ead-941b-442e-a064-44da65469129"
Template: "a2b91ead-941b-442e-a064-44da65469129"
Path: /sitecore/templates/Project/demo/Destinations/Destinations Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{D55A32C0-F2DF-4050-A31B-650C38B69DED}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "6a36aa05-137a-4ab2-be49-7337880da027"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{96E5F4BA-A2CF-4A4C-A4E7-64DA88226362}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{B1EE9B4B-86D9-4094-84C7-F7AE3ED9BBA5}"
              p:before="*"
              s:ds="query:$site/*[@@name='Data']/*[@@templatename='Hero Banner Folder']/Hero Banner"
              s:id="{4A430835-70A0-4117-85E5-B1CDF3C00B04}"
              s:par="GridParameters&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="headless-main" />
            <r
              uid="{E3795FCB-AE31-4F00-B3AC-25345F541A3C}"
              p:after="*[1=2]"
              s:ds=""
              s:id="{F56E0330-33D4-4C20-B377-58753C597940}"
              s:par="CSSStyles"
              s:ph="headless-main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250828T174015Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\asit_pani@epam.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\asit_pani@epam.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6ada147e-79ee-43ba-b83e-441176ad5dca"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\asit_pani@epam.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250828T200143Z
