---
ID: "60969fe1-f6c3-45ce-b6ed-98851927a408"
Parent: "d55a32c0-f2df-4050-a31b-650c38b69ded"
Template: "d55a32c0-f2df-4050-a31b-650c38b69ded"
Path: /sitecore/templates/Project/demo/Destinations/Region/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{04A4F95C-7645-4456-BD46-4CD523F984F5}"
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "41f15db1-3034-4536-b255-cd90a3daedf5"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{5A710E00-49F2-425E-B165-882C4E17604D}"
              p:before="*"
              s:ds="query:$site/*[@@name='Data']/*[@@templatename='Hero Banner Folder']/Hero Banner"
              s:id="{4A430835-70A0-4117-85E5-B1CDF3C00B04}"
              s:par="GridParameters&amp;FieldNames&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId"
              s:ph="headless-main" />
            <r
              uid="{799476B8-1B8C-41AA-8218-4204E73FF831}"
              p:after="*[1=2]"
              s:id="{F56E0330-33D4-4C20-B377-58753C597940}"
              s:ph="headless-main" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250828T174433Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "186f0e79-7b8e-4c1e-9f44-20a3bc2afca9"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\asit_pani@epam.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250828T195000Z
