---
ID: "5c577678-6ac2-4f76-8510-6f4b494f2b87"
Parent: "45ba67d8-d0cd-4bbd-8e4f-fd1d2d00aded"
Template: "c3b037a0-46e5-4b67-ac7a-a144b962a56f"
Path: /sitecore/layout/Placeholder Settings/Project/demo/Services
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250818T182521Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\asit_pani@epam.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\asit_pani@epam.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "06913513-2237-4ac6-a04d-c74c5e1d9676"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\asit_pani@epam.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250818T182521Z
